// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_api_keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: FirebaseApiKeys.webApiKey,
    appId: '1:586089510037:web:00b5d262c89a975dba179c',
    messagingSenderId: '586089510037',
    projectId: 'kiru-16',
    authDomain: 'kiru-16.firebaseapp.com',
    storageBucket: 'kiru-16.firebasestorage.app',
    measurementId: 'G-8E10HHGEP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: FirebaseApiKeys.androidApiKey,
    appId: '1:586089510037:android:abc18f2d86f8c328ba179c',
    messagingSenderId: '586089510037',
    projectId: 'kiru-16',
    storageBucket: 'kiru-16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: FirebaseApiKeys.iosApiKey,
    appId: '1:586089510037:ios:1bfe0ddcca4d806fba179c',
    messagingSenderId: '586089510037',
    projectId: 'kiru-16',
    storageBucket: 'kiru-16.firebasestorage.app',
    iosClientId: '586089510037-h0grarf55jlmk5lcm1l1s5kpshfae0ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: FirebaseApiKeys.iosApiKey,
    appId: '1:586089510037:ios:1bfe0ddcca4d806fba179c',
    messagingSenderId: '586089510037',
    projectId: 'kiru-16',
    storageBucket: 'kiru-16.firebasestorage.app',
    iosClientId: '586089510037-h0grarf55jlmk5lcm1l1s5kpshfae0ul.apps.googleusercontent.com',
    iosBundleId: 'com.example.kiru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: FirebaseApiKeys.webApiKey,
    appId: '1:586089510037:web:be08421a54f5ec02ba179c',
    messagingSenderId: '586089510037',
    projectId: 'kiru-16',
    authDomain: 'kiru-16.firebaseapp.com',
    storageBucket: 'kiru-16.firebasestorage.app',
    measurementId: 'G-3QQT40ENV1',
  );
}
